name: prico
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  socket_io_client: ^2.0.1
  shared_preferences: ^2.1.0
  flutter_syntax_view: ^4.0.0
  # Advanced Animation Packages
  flutter_staggered_animations: ^1.1.1
  rive: ^0.11.4
  lottie: ^2.7.0
  flutter_animate: ^4.2.0+1
  # 3D and Graphics Packages
  vector_math: ^2.1.4
  flutter_cube: ^0.1.1
  # Enhanced Chat Features
  emoji_picker_flutter: ^1.6.3
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_chat_bubble: ^2.0.2
  # UI Enhancement Packages
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
