version: '3.8'

services:
  # Redis for Socket.IO adapter and BullMQ
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # MongoDB (for local development - production uses Atlas)
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: prico
    volumes:
      - mongodb_data:/data/db

  # Y-WebSocket server for collaborative editing
  y-websocket:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "1234:1234"
    volumes:
      - ./server/y-websocket:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - redis

volumes:
  redis_data:
  mongodb_data: