version: '3.8'

services:

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    # Uses external MongoDB (Atlas); no local dependency.
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    volumes:
      - ./backend:/app
    networks:
      - prico-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    volumes:
      - ./frontend:/app
    networks:
      - prico-network

networks:
  prico-network:
    driver: bridge
